apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: deployment-viewer-sa
  namespace: sa-permissions-test

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: deployment-viewer-role
  namespace: sa-permissions-test
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list

---    

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: deployment-viewer-rb
  namespace: sa-permissions-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: deployment-viewer-role
subjects:
- kind: ServiceAccount
  name: sa-permisions-test
  namespace: deployment-viewer-sa
