apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-viewer-sa
  namespace: sa-permissions-test

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: pod-viewer-role
  namespace: sa-permissions-test
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: pod-viewer-rb
  namespace: sa-permissions-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-viewer-role
subjects:
- kind: ServiceAccount
  name: pod-viewer-sa
  namespace: sa-permissions-test
