apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: pod-viewer-rb
  namespace: sa-permissions-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-viewer-role
subjects:
- kind: ServiceAccount
  name: sa-permisions-test
  namespace: pod-viewer-sa
