apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: psp-test
---
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: psp-test-sa
  namespace: psp-test
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cr-use-psp-psp-nonpriv
rules:  
- apiGroups: ['policy']
  resources: ['podSecurityPolicy']
  verbs: ['use']        
  resourceNames:
  - psp-nonpriv
---    
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rb-psp-test
  namespace: psp-test
roleRef:
  kind: ClusterRole
  name: cr-use-psp-psp-nonpriv
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: psp-test-sa
  namespace: psp-test
